# run all tests

require './asterisk'
require './at'
require './backslash'
require './backtick'
require './comma'
require './dot'
require './exclamation'
require './helper'
require './minus'
require './parentheses'
require './percent'
require './plus'
require './quotes'
require './semicolon'
require './slash'
