# run all tests

require './asterisk'
require './at'
require './backslash'
require './backtick'
require './comma'
require './dot'
require './equals'
require './exclamation'
require './hash'
require './minus'
require './parentheses'
require './percent'
require './plus'
require './question'
require './quotes'
require './semicolon'
require './slash'
require './tilde'
